[package]
name = "terra-assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
terra-core.workspace = true

serde.workspace = true
ron.workspace = true
uuid.workspace = true
thiserror.workspace = true
log.workspace = true
gltf.workspace = true
rayon.workspace = true
glam.workspace = true
anyhow.workspace = true
