[package]
name = "terra-voxel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
terra-core = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }
