[package]
name = "terra-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
terra-core.workspace = true
terra-project.workspace = true
terra-assets.workspace = true
terra-voxel.workspace = true

wgpu.workspace = true
winit.workspace = true
glam.workspace = true
bytemuck.workspace = true
anyhow.workspace = true
log.workspace = true
rayon.workspace = true
serde.workspace = true
ron.workspace = true
image.workspace = true

[dev-dependencies]
pollster.workspace = true
half.workspace = true
