//! True 3D terrain: volumetric sculpting, boolean cave modifiers, and the
//! isosurface extraction that turns both back into triangles.
//!
//! # Why a second representation
//!
//! The heightfield in `terra-core` stores one height per column. That is the
//! right structure for eroded landscape -- hydraulic erosion is a 2D solve,
//! `.r16` interchanges with every terrain tool, and a 4096^2 world is 32 MB.
//! It also cannot, even in principle, represent an overhang, an arch, or a
//! cave: those need more than one surface per column.
//!
//! So this crate does not replace the heightfield, it layers over it. The
//! terrain a player walks on is still generated by ridged multifractal noise
//! and carved by the erosion solver; this crate adds the parts that a height
//! per column cannot express.
//!
//! # The field
//!
//! Everything is a signed distance field, **negative inside solid rock**,
//! composed from three layers ([`volume`]):
//!
//! ```text
//! base     the heightfield, read as a distance    -- free, already in memory
//! delta    sparse voxel offsets                   -- freeform 3D sculpting
//! stack    ordered boolean modifiers              -- caves, non-destructive
//! ```
//!
//! evaluated as `stack(base(p) + delta(p))`. Sculpting lands under the
//! modifiers, so carving a tunnel never destroys the clay it passes through
//! and deleting the tunnel restores it.
//!
//! # The pipeline
//!
//! ```text
//! 1. select     octree descent picks visible chunks and their LOD  [lod]
//! 2. sample     evaluate the composed field on each chunk lattice  [volume]
//! 3. extract    Surface Nets -> vertices + indices                 [surface_nets, gpu]
//! 4. draw       one draw_indexed_indirect over the whole set       [lod]
//! ```
//!
//! Step 3 has two implementations that must agree: a CPU reference in
//! [`surface_nets`] and a compute pipeline in [`gpu`]. The CPU one is the
//! oracle -- it is what the tests check the shader against, and what builds
//! physics colliders, where a GPU readback would stall the frame.
//!
//! # What is deliberately not here
//!
//! * **Redistancing.** Heavy sculpting leaves a field that is correctly signed
//!   but no longer metric. See the note in [`brush`].
//! * **Persistence.** The delta field and modifier stack have no on-disk
//!   format yet; they belong under `edits/` in the project layout, beside the
//!   sculpt deltas and road splines that are already there.

pub mod brush;
pub mod gpu;
pub mod lod;
pub mod modifier;
pub mod noise;
pub mod sdf;
pub mod surface_nets;
pub mod volume;

pub use brush::{Brush, Stroke};
pub use lod::{DrawIndexedIndirect, Frustum, LodConfig, Node};
pub use modifier::{Aabb, Modifier, ModifierStack, Op, Shape, Tube, TubePoint};
pub use noise::{NoiseField, NoiseImage, NoisePattern};
pub use surface_nets::{Mesh, SampleGrid, chunk_grid, extract};
pub use volume::{BaseField, CHUNK_DIM, DeltaField, VoxelVolume};
